# -*- coding: utf-8 -*-
"""
_export_marketing_geom.py — bake the marketing home page's static assets into web/.

Two jobs, both author-time only. Nothing here runs at request time: the public page
must render the real trace shapes with NO Supabase call and no runtime fetch.

  1. scratch/_home_geom.json  ->  web/lib/marketingGeom.js
     A straight re-emit. The numbers are NOT re-derived here; _home_geom.py owns the
     perturbation table and the radar display ranges, and duplicating either would let
     the two drift apart. Two things this does that a copy would not:
       - decimates the whole-lap polyline (1762 samples into a 900 unit viewBox is
         about two points per unit, so every 2nd sample is kept)
       - rounds every coordinate to one decimal so no float noise reaches the bundle
     The per-phase slices in the JSON are deliberately NOT exported: D23 replaced the
     three per-card slices with the single whole-lap chart, so nothing reads them.

  2. assets/icon/Swimnetics_icon.svg  ->  web/public/swimnetics-mark.png
                                          web/app/icon.png (32px)
                                          web/app/apple-icon.png (180px)
     That "SVG" is a 1004x960 PNG base64-embedded in an SVG wrapper, so the wrapper is
     dropped and the inner raster committed directly.

Run from the repo root:  python scratch/_export_marketing_geom.py
"""
import base64
import io
import json
import os
import re

from PIL import Image

GEOM_JSON = 'scratch/_home_geom.json'
OUT_JS = 'web/lib/marketingGeom.js'
MARK_SVG = 'assets/icon/Swimnetics_icon.svg'
MARK_PNG = 'web/public/swimnetics-mark.png'
ICON_32 = 'web/app/icon.png'
ICON_180 = 'web/app/apple-icon.png'
FAVICON = 'web/app/favicon.ico'

HEADER = '''// Marketing home page geometry. GENERATED by scratch/_export_marketing_geom.py from
// scratch/_home_geom.json. Do not hand edit; re-run the exporter instead.
//
// Source: one coach-marked butterfly 25, session 85b18b3f, recorded 2026-08-20. All four
// phase boundaries on it are `manual`, so the windows below are a coach's marks and not
// detector output.
//
// READ THIS BEFORE WRITING COPY AGAINST IT:
//   - Trace GEOMETRY is real and unmodified. The whole-lap polyline and the five cycle
//     polylines are that swim's actual velocity profile.
//   - Every value that could be PRINTED was deterministically perturbed in _home_geom.py,
//     so no number derived from here is a real athlete measurement.
//   - The radar "usual range" rings are DRAWN, not measured. That athlete has only two
//     other same-stroke swims against the five the product actually uses.
//   => Nothing derived from this file may therefore be presented as an unmodified
//      measurement, and no badge on the page may claim it is one. The copy check in
//      scratch/marketing_render_check.mjs enforces the absence of that claim.
//
// No athlete name appears here or anywhere downstream of it.
'''


def decimate(poly, step):
    """Keep every `step`-th point, always keeping the last one."""
    pts = poly.split(' ')
    kept = pts[::step]
    if kept[-1] != pts[-1]:
        kept.append(pts[-1])
    return ' '.join(kept)


def reround(poly):
    out = []
    for p in poly.split(' '):
        x, y = p.split(',')
        out.append('%.1f,%.1f' % (float(x), float(y)))
    return ' '.join(out)


def js(value, indent=2):
    """Minimal JSON -> JS object literal. Keys here are all plain identifiers."""
    return json.dumps(value, indent=indent, ensure_ascii=True)


def export_geometry():
    g = json.load(open(GEOM_JSON, encoding='utf-8'))

    whole = dict(g['whole'])
    raw = whole['poly']
    whole['poly'] = reround(decimate(raw, 2))

    cycles = [{'n': c['n'], 'poly': reround(c['poly']), 'dur': c['dur']}
              for c in g['cycles']]

    out = {
        'whole': whole,
        'cycles': cycles,
        'oddCycle': g['odd_cycle'],
        'radars': {k: [{'label': a['label'], 'r': a['r'], 'ring': a['ring']}
                       for a in v]
                   for k, v in g['radars'].items()},
    }

    body = HEADER + '\nconst MARKETING_GEOM = Object.freeze(' + js(out) + ');\n\n' \
        + 'export default MARKETING_GEOM;\n'
    open(OUT_JS, 'w', encoding='utf-8', newline='\n').write(body)

    print('whole poly : %d pts -> %d pts, %.1f KB'
          % (raw.count(' ') + 1, whole['poly'].count(' ') + 1,
             len(whole['poly']) / 1024))
    print('cycles     : %d (undecimated)' % len(cycles))
    print('radars     : %s' % {k: len(v) for k, v in out['radars'].items()})
    print('module     : %s, %.1f KB' % (OUT_JS, len(body) / 1024))


def export_mark():
    svg = open(MARK_SVG, encoding='utf-8').read()
    m = re.search(r'base64,([A-Za-z0-9+/=\s]+?)"', svg)
    assert m, 'no base64 payload in %s' % MARK_SVG
    raw = base64.b64decode(re.sub(r'\s+', '', m.group(1)))
    assert raw[:8] == b'\x89PNG\r\n\x1a\n', 'embedded payload is not a PNG'
    open(MARK_PNG, 'wb').write(raw)

    im = Image.open(io.BytesIO(raw)).convert('RGBA')
    for path, px in ((ICON_32, 32), (ICON_180, 180)):
        # Square canvas so the browser does not letterbox it, mark centred.
        side = max(im.size)
        canvas = Image.new('RGBA', (side, side), (0, 0, 0, 0))
        canvas.paste(im, ((side - im.size[0]) // 2, (side - im.size[1]) // 2))
        canvas.resize((px, px), Image.LANCZOS).save(path)

    if os.path.exists(FAVICON):
        os.remove(FAVICON)
        print('removed    : %s (icon.png/apple-icon.png replace it)' % FAVICON)

    print('mark       : %s %dx%d, %.1f KB (wrapper dropped, was %.1f KB)'
          % (MARK_PNG, im.size[0], im.size[1], len(raw) / 1024,
             os.path.getsize(MARK_SVG) / 1024))
    print('icons      : %s 32px, %s 180px' % (ICON_32, ICON_180))


if __name__ == '__main__':
    export_geometry()
    export_mark()
